name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install libfftw3-dev
      - name: Build shared library
        run: |
          make -j$(nproc) all
      - name: Run tests
        run: |
          make test
      - name: Lint
        run: |
          make lint

    container:
      image: tensorflow/tensorflow:custom-op-gpu-ubuntu16
