name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: tensorflow/tensorflow:custom-op-gpu-ubuntu16

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          make dependencies
      - name: Build shared library
        run: |
          make -j$(nproc) lib
      # - name: Run tests
      #   run: |
      #     make test
      # - name: Lint
      #   run: |
      #     make lint
      - name: Build pip package
        run: |
          make pip_pkg
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: artifacts/
      # - name: Publish to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
