name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint-code:

    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint code
        run: |
          make lint

  build-docker:

    name: Build Docker environment
    needs: lint-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get package version
        run: |
          echo "package_version=$(cat ./VERSION)" >> $GITHUB_ENV

      - name: Setup Buildx action
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tools/docker/build_env.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.package_version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ env.package_version }}
          cache-to: type=inline

  build-lib:

    name: Build shared library
    needs: build-docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get package version
        run: |
          echo "package_version=$(cat ./VERSION)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ env.package_version }}

      - name: Build shared library
        run: |
          ./tools/build/run_in_build_env make -j$(nproc) lib

      - name: Upload shared library
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: ./tensorflow_nufft/python/ops/_nufft_ops.so

  build-pip:

    name: Build pip package
    needs: [build-docker, build-lib]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        py-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get package version
        run: |
          echo "package_version=$(cat ./VERSION)" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ env.package_version }}

      - name: Download shared library
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: ./tensorflow_nufft/python/ops
      
      - name: Build pip package
        run: |
          ./tools/build/run_in_build_env make pip_pkg PY_VERSION=${{ matrix.py-version }}
    
      - name: Upload pip package
        uses: actions/upload-artifact@v2
        with:
          name: pip_pkg
          path: ./artifacts/*.whl

      # - name: Publish to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: artifacts/

      # - name: Publish to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
  
